/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.91
 * Generated at: 2018-11-21 15:26:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head></head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>会员注册</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\" type=\"text/css\" />\r\n");
      out.write("<script src=\"js/jquery-1.11.3.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<!-- 引入表单校验jquery插件 -->\r\n");
      out.write("<script src=\"js/jquery.validate.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<!-- 引入自定义css文件 style.css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("\tmargin-top: 20px;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".carousel-inner .item img {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("font {\r\n");
      out.write("\tcolor: #3164af;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\tfont-weight: normal;\r\n");
      out.write("\tpadding: 0 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".error{\r\n");
      out.write("\tcolor:red\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t//自定义校验规则\r\n");
      out.write("\t$.validator.addMethod(\r\n");
      out.write("\t\t//规则的名称\r\n");
      out.write("\t\t\"checkUsername\",\r\n");
      out.write("\t\t//校验的函数\r\n");
      out.write("\t\tfunction(value,element,params){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//定义一个标志\r\n");
      out.write("\t\t\tvar flag = false;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//value:输入的内容\r\n");
      out.write("\t\t\t//element:被校验的元素对象\r\n");
      out.write("\t\t\t//params：规则对应的参数值\r\n");
      out.write("\t\t\t//目的：对输入的username进行ajax校验\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\"async\":false,\r\n");
      out.write("\t\t\t\t\"url\":\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/checkUsername\",\r\n");
      out.write("\t\t\t\t\"data\":{\"username\":value},\r\n");
      out.write("\t\t\t\t\"type\":\"POST\",\r\n");
      out.write("\t\t\t\t\"dataType\":\"json\",\r\n");
      out.write("\t\t\t\t\"success\":function(data){\r\n");
      out.write("\t\t\t\t\tflag = data.isExist;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//返回false代表该校验器不通过\r\n");
      out.write("\t\t\treturn !flag;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$(\"#myform\").validate({\r\n");
      out.write("\t\t\trules:{\r\n");
      out.write("\t\t\t\t\"username\":{\r\n");
      out.write("\t\t\t\t\t\"required\":true,\r\n");
      out.write("\t\t\t\t\t\"checkUsername\":true\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t\"password\":{\r\n");
      out.write("\t\t\t\t\t\"required\":true,\r\n");
      out.write("\t\t\t\t\t\"rangelength\":[6,12]\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t\"repassword\":{\r\n");
      out.write("\t\t\t\t\t\"required\":true,\r\n");
      out.write("\t\t\t\t\t\"rangelength\":[6,12],\r\n");
      out.write("\t\t\t\t\t\"equalTo\":\"#password\"\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t\"email\":{\r\n");
      out.write("\t\t\t\t\t\"required\":true,\r\n");
      out.write("\t\t\t\t\t\"email\":true\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t\"sex\":{\r\n");
      out.write("\t\t\t\t\t\"required\":true\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tmessages:{\r\n");
      out.write("\t\t\t\t\"username\":{\r\n");
      out.write("\t\t\t\t\t\"required\":\"用户名不能为空\",\r\n");
      out.write("\t\t\t\t\t\"checkUsername\":\"用户名已存在\"\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t\"password\":{\r\n");
      out.write("\t\t\t\t\t\"required\":\"密码不能为空\",\r\n");
      out.write("\t\t\t\t\t\"rangelength\":\"密码长度6-12位\"\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t\"repassword\":{\r\n");
      out.write("\t\t\t\t\t\"required\":\"密码不能为空\",\r\n");
      out.write("\t\t\t\t\t\"rangelength\":\"密码长度6-12位\",\r\n");
      out.write("\t\t\t\t\t\"equalTo\":\"两次密码不一致\"\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t\"email\":{\r\n");
      out.write("\t\t\t\t\t\"required\":\"邮箱不能为空\",\r\n");
      out.write("\t\t\t\t\t\"email\":\"邮箱格式不正确\"\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 引入header.jsp -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\"\r\n");
      out.write("\t\tstyle=\"width: 100%; background: url('image/regist_bg.jpg');\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-2\"></div>\r\n");
      out.write("\t\t\t<div class=\"col-md-8\"\r\n");
      out.write("\t\t\t\tstyle=\"background: #fff; padding: 40px 80px; margin: 30px; border: 7px solid #ccc;\">\r\n");
      out.write("\t\t\t\t<font>会员注册</font>USER REGISTER\r\n");
      out.write("\t\t\t\t<form id=\"myform\" class=\"form-horizontal\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/register\" method=\"post\" style=\"margin-top: 5px;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"username\" class=\"col-sm-2 control-label\">用户名</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"username\" name=\"username\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"请输入用户名\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"inputPassword3\" class=\"col-sm-2 control-label\">密码</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" id=\"password\" name=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"请输入密码\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"confirmpwd\" class=\"col-sm-2 control-label\">确认密码</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" id=\"confirmpwd\" name=\"repassword\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"请输入确认密码\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"inputEmail3\" class=\"col-sm-2 control-label\">Email</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"email\" class=\"form-control\" id=\"inputEmail3\" name=\"email\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Email\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"usercaption\" class=\"col-sm-2 control-label\">姓名</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"usercaption\" name=\"name\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"请输入姓名\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group opt\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"inlineRadio1\" class=\"col-sm-2 control-label\">性别</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"radio-inline\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"sex\" id=\"sex1\" value=\"male\" >男\r\n");
      out.write("\t\t\t\t\t\t\t</label> \r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"radio-inline\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"sex\" id=\"sex2\" value=\"female\">女\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"error\" for=\"sex\" style=\"display:none \">您没有第三种选择</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"date\" class=\"col-sm-2 control-label\">出生日期</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"date\" class=\"form-control\" name=\"birthday\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"date\" class=\"col-sm-2 control-label\">验证码</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"checkCode\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"./image/captcha.jhtml\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-offset-2 col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" width=\"100\" value=\"注册\" name=\"submit\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"background: url('./images/register.gif') no-repeat scroll 0 0 rgba(0, 0, 0, 0); height: 35px; width: 100px; color: white;\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-2\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 引入footer.jsp -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
